:ambulance: Patch C lib builds on `arm64` Macs
Fixes:
```
running build_ext
building '451ad3e1dda0bf230bf3__mypyc' extension
creating /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/temp.macosx-12.2-arm64-cpython-310
creating /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/temp.macosx-12.2-arm64-cpython-310/build
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-build-env-mfruipoz/overlay/lib/python3.10/site-packages/mypyc/lib-rt -Ibuild -I/Users/tobiasz/Repositories/cat-app/.venv/include -I/Users/tobiasz/.pyenv/versions/3.10.0/include/python3.10 -c build/__native_451ad3e1dda0bf230bf3.c -o /private/var/folders/js/4mzt32c52js62__2kdsnpyxh0000gn/T/pip-install-sn7flr1s/structlog-sentry-logger_386daca57ab0482f9e4d32665b4b4aa3/build/temp.macosx-12.2-arm64-cpython-310/build/__native_451ad3e1dda0bf230bf3.o -O3 -g1 -Werror -Wno-unused-function -Wno-unused-label -Wno-unreachable-code -Wno-unused-variable -Wno-unused-command-line-argument -Wno-unknown-warning-option
build/__native_451ad3e1dda0bf230bf3.c:2722:10: error: variable 'cpy_r_r34' set but not used [-Werror,-Wunused-but-set-variable]
    char cpy_r_r34;
         ^
build/__native_451ad3e1dda0bf230bf3.c:11071:15: error: variable 'cpy_r_r312' set but not used [-Werror,-Wunused-but-set-variable]
    PyObject *cpy_r_r312;
              ^
2 errors generated.
error: command '/usr/bin/clang' failed with exit code 1
```