:rotating_light: :wrench: Export requirements files via `--output` flag
Fixes:
```
================================== log start ===================================
ERROR: Invalid requirement: 'Creating virtualenv structlog-sentry-logger in /home/runner/work/structlog-sentry-logger/structlog-sentry-logger/.venv' (from line 1 of requirements.txt)
Hint: It looks like a path. File 'Creating virtualenv structlog-sentry-logger in /home/runner/work/structlog-sentry-logger/structlog-sentry-logger/.venv' does not exist.

=================================== log end ====================================
```

see: python-poetry/poetry#6275