:green_heart: :pushpin: Pin Windows runner to Windows Server 2019
Fixes broken package building on Windows that started on 2022-01-22
at 6:07 AM PST.

Example job log:
 ```
 Run make package
 /usr/bin/bash: shasum: command not found
 tox -e package
 .package create: D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\.package
 .package installdeps: poetry-core>=1.0.0, mypy>=0.910, setuptools>=58.1.0, orjson>=3.6.4
 package create: D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package
 package installdeps: poetry >= 1.1.2, mypy >= 0.910, twine >= 1.12.1, orjson >= 3.6.4, readme-renderer[md] >= 24.0
 package inst: D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\.tmp\package\1\structlog-sentry-logger-0.17.2.dev1643378899.tar.gz
 package installed: bleach==4.1.0,CacheControl==0.12.10,cachy==0.3.0,certifi==2021.10.8,cffi==1.15.0,charset-normalizer==2.0.10,cleo==0.8.1,clikit==0.6.2,cmarkgfm==0.6.0,colorama==0.4.4,commonmark==0.9.1,crashtest==0.3.1,distlib==0.3.4,docutils==0.18.1,filelock==3.4.2,gitdb==4.0.9,GitPython==3.1.26,html5lib==1.1,idna==3.3,importlib-metadata==4.10.1,keyring==21.8.0,lockfile==0.12.2,msgpack==1.0.3,mypy==0.931,mypy-extensions==0.4.3,orjson==3.6.6,packaging==20.9,pastel==0.2.1,pexpect==4.8.0,pkginfo==1.8.2,platformdirs==2.4.1,poetry==1.1.12,poetry-core==1.0.7,ptyprocess==0.7.0,pycparser==2.21,Pygments==2.11.2,pylev==1.4.0,pyparsing==3.0.7,python-dotenv==0.19.2,pywin32-ctypes==0.2.0,readme-renderer==32.0,requests==2.27.1,requests-toolbelt==0.9.1,rfc3986==2.0.0,rich==11.0.0,sentry-sdk==1.5.4,shellingham==1.4.0,six==1.16.0,smmap==5.0.0,structlog==21.5.0,structlog-sentry-logger @ file:///D:/a/structlog-sentry-logger/structlog-sentry-logger/.tox/.tmp/package/1/structlog-sentry-logger-0.17.2.dev1643378899.tar.gz,tomli==2.0.0,tomlkit==0.8.0,tqdm==4.62.3,twine==3.7.1,typing_extensions==4.0.1,urllib3==1.26.8,virtualenv==20.13.0,webencodings==0.5.1,zipp==3.7.0
 package run-test-pre: PYTHONHASHSEED='572'
 package run-test: commands[0] | poetry build
 Building structlog-sentry-logger (0.17.2.dev.1643378899)
   - Building sdist
 The system cannot find the path specified.
   - Built structlog-sentry-logger-0.17.2.dev1643378899.tar.gz
   - Building wheel
 The system cannot find the path specified.
 running build
 running build_py
 creating D:\a\structlog-sentry-logger\structlog-sentry-logger\build\lib.win-amd64-3.8
 creating D:\a\structlog-sentry-logger\structlog-sentry-logger\build\lib.win-amd64-3.8\structlog_sentry_logger
 copying structlog_sentry_logger\structlog_sentry.py -> D:\a\structlog-sentry-logger\structlog-sentry-logger\build\lib.win-amd64-3.8\structlog_sentry_logger
 copying structlog_sentry_logger\_config.py -> D:\a\structlog-sentry-logger\structlog-sentry-logger\build\lib.win-amd64-3.8\structlog_sentry_logger
 copying structlog_sentry_logger\_feature_flags.py -> D:\a\structlog-sentry-logger\structlog-sentry-logger\build\lib.win-amd64-3.8\structlog_sentry_logger
 copying structlog_sentry_logger\__init__.py -> D:\a\structlog-sentry-logger\structlog-sentry-logger\build\lib.win-amd64-3.8\structlog_sentry_logger
 copying structlog_sentry_logger\py.typed -> D:\a\structlog-sentry-logger\structlog-sentry-logger\build\lib.win-amd64-3.8\structlog_sentry_logger
 running build_ext
 Traceback (most recent call last):
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\setup.py", line 49, in <module>
     setup(**setup_kwargs)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\__init__.py", line 155, in setup
     return distutils.core.setup(**attrs)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
     return run_commands(dist)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
     dist.run_commands()
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
     self.run_command(cmd)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
     cmd_obj.run()
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
     self.run_command(cmd_name)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
     self.distribution.run_command(command)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
     cmd_obj.run()
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
     _build_ext.run(self)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
     self.build_extensions()
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
     self._build_extensions_serial()
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
     self.build_extension(ext)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
     _build_ext.build_extension(self, ext)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
     objects = self.compiler.compile(sources,
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
     self.initialize()
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
     vc_env = _get_vc_env(plat_spec)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
     return _msvc14_get_vc_env(plat_spec)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
     raise distutils.errors.DistutilsPlatformError(
 setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

   CalledProcessError

   Command '['D:/a/structlog-sentry-logger/structlog-sentry-logger/.tox/package/Scripts/python.exe', 'D:\\a\\structlog-sentry-logger\\structlog-sentry-logger\\setup.py', 'build', '-b', 'D:\\a\\structlog-sentry-logger\\structlog-sentry-logger\\build']' returned non-zero exit status 1.

   at c:\hostedtoolcache\windows\python\3.8.10\x64\lib\subprocess.py:364 in check_call
 Traceback (most recent call last):
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\clikit\console_application.py", line 131, in run
     status_code = command.handle(parsed_args, io)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\clikit\api\command\command.py", line 120, in handle
     status_code = self._do_handle(args, io)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\clikit\api\command\command.py", line 171, in _do_handle
     return getattr(handler, handler_method)(args, io, self)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\cleo\commands\command.py", line 92, in wrap_handle
     return self.handle()
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\poetry\console\commands\build.py", line 36, in handle
     builder.build(fmt, executable=self.env.python)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\poetry\core\masonry\builder.py", line 35, in build
     builder(self._poetry, executable=executable).build()
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\poetry\core\masonry\builders\wheel.py", line 103, in build
     self._build(zip_file)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\poetry\core\masonry\builders\wheel.py", line 135, in _build
     self._run_build_command(setup)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\poetry\core\masonry\builders\wheel.py", line 163, in _run_build_command
     subprocess.check_call(
   File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\subprocess.py", line 364, in check_call
     raise CalledProcessError(retcode, cmd)
 poetry.utils._compat.CalledProcessError: Command '['D:/a/structlog-sentry-logger/structlog-sentry-logger/.tox/package/Scripts/python.exe', 'D:\\a\\structlog-sentry-logger\\structlog-sentry-logger\\setup.py', 'build', '-b', 'D:\\a\\structlog-sentry-logger\\structlog-sentry-logger\\build']' returned non-zero exit status 1.

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\runpy.py", line 194, in _run_module_as_main
     return _run_code(code, main_globals, None,
   File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\runpy.py", line 87, in _run_code
     exec(code, run_globals)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\Scripts\poetry.EXE\__main__.py", line 7, in <module>
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\poetry\console\__init__.py", line 5, in main
     return Application().run()
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\clikit\console_application.py", line 142, in run
     trace.render(io, simple=isinstance(e, CliKitException))
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\clikit\ui\components\exception_trace.py", line 232, in render
     return self._render_exception(io, self._exception)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\clikit\ui\components\exception_trace.py", line 269, in _render_exception
     self._render_snippet(io, current_frame)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\clikit\ui\components\exception_trace.py", line 289, in _render_snippet
     self._render_line(io, code_line)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\clikit\ui\components\exception_trace.py", line 402, in _render_line
     io.write_line("{}{}".format(indent * " ", line))
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\cleo\io\io_mixin.py", line 65, in write_line
     super(IOMixin, self).write_line(string, flags)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\clikit\api\io\io.py", line 66, in write_line
     self._output.write_line(string, flags=flags)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\clikit\api\io\output.py", line 69, in write_line
     self.write(string, flags=flags, new_line=True)
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\clikit\api\io\output.py", line 61, in write
     self._stream.write(to_str(formatted))
   File "D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\lib\site-packages\clikit\io\output_stream\stream_output_stream.py", line 24, in write
     self._stream.write(string)
   File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\encodings\cp1252.py", line 19, in encode
     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
 UnicodeEncodeError: 'charmap' codec can't encode character '\u2502' in position 10: character maps to <undefined>
 ERROR: InvocationError for command 'D:\a\structlog-sentry-logger\structlog-sentry-logger\.tox\package\Scripts\poetry.EXE' build (exited with code 1)
 ___________________________________ summary ___________________________________
 ERROR:   package: commands failed
 mingw32-make: *** [Makefile:154: package] Error 1
 Error: Process completed with exit code 1.
 ```