:rotating_light: Fix build error for `tox` testenv: `package`
Example error log:
```
poetry run tox --recreate -e package --
package recreate: /Users/TeofiloZosa/Developer/SonoSim/CorSAIR/utils/structlog-sentry-logger/.tox/package
package installdeps: poetry >= 1.1.2, twine >= 1.12.1, readme-renderer[md] >= 24.0
package installed: backports.entry-points-selectable==1.1.0,bleach==4.0.0,CacheControl==0.12.6,cachy==0.3.0,certifi==2021.5.30,cffi==1.14.6,charset-normalizer==2.0.4,cleo==0.8.1,clikit==0.6.2,cmarkgfm==0.5.3,colorama==0.4.4,crashtest==0.3.1,distlib==0.3.2,docutils==0.17.1,filelock==3.0.12,html5lib==1.1,idna==3.2,importlib-metadata==1.7.0,keyring==21.8.0,lockfile==0.12.2,msgpack==1.0.2,packaging==20.9,pastel==0.2.1,pexpect==4.8.0,pkginfo==1.7.1,platformdirs==2.2.0,poetry==1.1.7,poetry-core==1.0.3,ptyprocess==0.7.0,pycparser==2.20,Pygments==2.9.0,pylev==1.4.0,pyparsing==2.4.7,readme-renderer==29.0,requests==2.26.0,requests-toolbelt==0.9.1,rfc3986==1.5.0,shellingham==1.4.0,six==1.16.0,tomlkit==0.7.2,tqdm==4.62.0,twine==3.3.0,urllib3==1.26.6,virtualenv==20.7.0,webencodings==0.5.1,zipp==3.5.0
package run-test-pre: PYTHONHASHSEED='3700683522'
package run-test: commands[0] | poetry build
Building structlog-sentry-logger (0.8.1)
  - Building sdist
  - Built structlog-sentry-logger-0.8.1.tar.gz
  - Building wheel
Traceback (most recent call last):
  File "build.py", line 1, in <module>
    import mypyc.build
ModuleNotFoundError: No module named 'mypyc'

  CalledProcessError

  Command '['/Users/TeofiloZosa/Developer/SonoSim/CorSAIR/utils/structlog-sentry-logger/.tox/package/bin/python', 'build.py']' returned non-zero exit status 1.

  at ~/.pyenv/versions/3.7.9/lib/python3.7/subprocess.py:363 in check_call
       359│     if retcode:
       360│         cmd = kwargs.get("args")
       361│         if cmd is None:
       362│             cmd = popenargs[0]
    →  363│         raise CalledProcessError(retcode, cmd)
       364│     return 0
       365│
       366│
       367│ def check_output(*popenargs, timeout=None, **kwargs):
ERROR: InvocationError for command /Users/TeofiloZosa/Developer/SonoSim/CorSAIR/utils/structlog-sentry-logger/.tox/package/bin/poetry build (exited with code 1)
__________________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________________
ERROR:   package: commands failed
make: *** [tox-package] Error 1
```